---
title: "Documentation"
author: "K. van Splunter"
date: "24 March 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment

This app is part of the Peer Assignment for the Coursera course *Developing Data Products*.
The goal of the assignment is to create a simple app with *Shiny* and to create a corresponding pitch presentation.

## App

This app creates a plot with a linear regression line based on the dataset **swiss**, which is one of the default datasets in R. A short overview of the dataset can be found on [this][1] page.
The full code for the app and the pitch presentation can be found [here][2].
The webbased presentation can be [viewed][3].

## What to do

As mentioned, the app creates a plot with a linear regression line. The outcome variable is *Fertility*. The predictor variable can be selected by the user. This is done in the dropdown-menu on the left side of the screen.
After the variable of choice is selected, the user must hit the **Done** button for the plot to be shown.
By default, the predictor variable is set to be the *Agriculture* variable.


[1]: https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/swiss.html "this"
[2]: https://github.com/kobe04/DevDataProductWeek4 "here"
[3]: https://kobe04.github.io/DevDataProductWeek4/Pitch.html "viewed"